### PR TITLE
seems like Github changed the .tar.gz url

### PR DESCRIPTION
**Pull request by Nakilon**

### CODE REVIEW

**Comment by Nakilon** [comment]
Then I edited to `/archive/v${VIPS_VERSION}.tar.gz` but now it says

```
/bin/sh: ./configure: not found
```
```
/ # find /tmp/ -name *configure*
/tmp/libvips-8.6.4/configure.ac
```

I'm confused, how did it work at all?

**Comment by Nakilon** [comment]
Oh the problem was in that the repo has moved to the "libvips" user.  
About the `pipefail` see the recommendation here: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

**Comment by felixbuenemann** [comment]
Yeah, libvips moved into a new team.

**Comment by felixbuenemann** [comment]
The pipefail is a good addition.

**Pull request merged**
